### ISSUE TITLE
Did not handle version v.1.2.3

### ISSUE THREAD

**Issue by redkhalil** [nowsprinting/check-version-format-action#295]
A dot after the `v` is considered valid.

**Comment by nowsprinting** [comment]
Have you tried the prefix option?

```yaml
- uses: nowsprinting/check-version-format-action@v3
  id: version
  with:
    prefix: 'v.'
```
